import type { SmileCardData } from "@/types";

export const SMILE_CARDS: readonly SmileCardData[] = [
  // 가족 — 익숙해서 더 웃긴 우리 집 이야기
  {
    id: "family-01",
    targetIds: ["family"],
    category: "유머",
    emoji: "📺",
    eyebrow: "우리 집 미제 사건",
    message: "리모컨이 또 사라졌습니다.\n유력한 용의자는… 깔고 앉은 사람!",
    prompt: "모두 자리에서 살짝 일어나며 수사해보세요.",
    gradient: "from-[#FFF0A8] to-[#FFD54F]",
  },
  {
    id: "family-02",
    targetIds: ["family"],
    category: "농담",
    emoji: "🍗",
    eyebrow: "가족만 아는 생존 법칙",
    message: "냉장고 속 마지막 한 입은\n이름 써둔 사람이 임자래요!",
    prompt: "내 간식에 오늘부터 명찰을 붙여보세요.",
    gradient: "from-[#FFE4C7] to-[#FFC878]",
  },
  {
    id: "family-03",
    targetIds: ["family"],
    category: "칭찬",
    emoji: "🏠",
    eyebrow: "집을 집답게 만드는 사람",
    message: "우리 집이 편안한 이유 중 하나는\n당신이 여기 있기 때문이에요.",
    prompt: "평소 쑥스러워 못 했던 진심을 툭 건네보세요.",
    gradient: "from-[#FFE5D8] to-[#FFC6B0]",
  },
  {
    id: "family-04",
    targetIds: ["family"],
    category: "미션",
    emoji: "🎭",
    eyebrow: "우리 집 성대모사 대회",
    message: "가족 중 한 명의 단골 멘트를\n똑같이 따라 해보기!",
    prompt: "놀리는 대신 애정을 듬뿍 담는 것이 규칙이에요.",
    gradient: "from-[#E9E2FF] to-[#CFC2FF]",
  },
  {
    id: "family-05",
    targetIds: ["family"],
    category: "유머",
    emoji: "📱",
    eyebrow: "가족 단톡방 속보",
    message: "오늘의 가족 공지입니다.\n당신이 웃을 때까지 해산 금지!",
    prompt: "공지사항 읽듯 엄숙하게 발표해주세요.",
    gradient: "from-[#DFF3FF] to-[#A9DBF8]",
  },
  {
    id: "family-06",
    targetIds: ["family"],
    category: "응원",
    emoji: "🫶",
    eyebrow: "가장 가까운 우리 편",
    message: "밖에서 무슨 일이 있었든\n집에서는 내가 당신 편이에요.",
    prompt: "말끝에 손가락 하트를 하나 붙여주세요.",
    gradient: "from-[#E0F6E6] to-[#AFE0BC]",
  },

  // 친구 — 흑역사까지 웃음이 되는 사이
  {
    id: "friend-01",
    targetIds: ["friend"],
    category: "유머",
    emoji: "🤪",
    eyebrow: "우정 연구소의 결론",
    message: "우리가 친해진 이유 알아?\n서로의 이상함을 존중해서야.",
    prompt: "가장 이상한 표정으로 고개를 끄덕여주세요.",
    gradient: "from-[#FFF0A8] to-[#FFD54F]",
  },
  {
    id: "friend-02",
    targetIds: ["friend"],
    category: "칭찬",
    emoji: "🛟",
    eyebrow: "인생의 든든한 안전장치",
    message: "내 흑역사를 다 알고도 옆에 있다니,\n너 정말 의리 있다!",
    prompt: "둘만 아는 흑역사는 공개하지 않는 게 우정이에요.",
    gradient: "from-[#FFE2D9] to-[#FFBEAD]",
  },
  {
    id: "friend-03",
    targetIds: ["friend"],
    category: "미션",
    emoji: "📢",
    eyebrow: "5초 홈쇼핑 미션",
    message: "내 친구의 장점을\n홈쇼핑 상품처럼 팔아보기!",
    prompt: "‘지금 아니면 못 만나요!’로 마무리하세요.",
    gradient: "from-[#E8E2FF] to-[#CABFFF]",
  },
  {
    id: "friend-04",
    targetIds: ["friend"],
    category: "농담",
    emoji: "📶",
    eyebrow: "우정 와이파이 연결 중",
    message: "좋은 친구는 와이파이 같대.\n안 보여도 연결되어 있으니까!",
    prompt: "비밀번호는 ‘평생친구’라고 알려주세요.",
    gradient: "from-[#DFF3FF] to-[#A8D9F5]",
  },
  {
    id: "friend-05",
    targetIds: ["friend"],
    category: "유머",
    emoji: "🧓",
    eyebrow: "미래에서 온 메시지",
    message: "우리 나중에 할머니·할아버지가 돼도\n이 얘기로 또 웃고 있겠다.",
    prompt: "갑자기 허리를 짚고 노인 연기를 해보세요.",
    gradient: "from-[#FFF1CD] to-[#FFD68E]",
  },
  {
    id: "friend-06",
    targetIds: ["friend"],
    category: "응원",
    emoji: "🥊",
    eyebrow: "친구 사용 설명서",
    message: "네가 지치면 내가 대신 화내주고,\n괜찮아지면 같이 웃어줄게.",
    prompt: "주먹을 가볍게 맞대며 팀워크를 충전하세요.",
    gradient: "from-[#DFF5E8] to-[#AFDFC1]",
  },

  // 연인 — 오글거림도 둘이면 로맨스
  {
    id: "lover-01",
    targetIds: ["lover"],
    category: "유머",
    emoji: "🔋",
    eyebrow: "애정 배터리 긴급 점검",
    message: "내 애정 배터리가 1% 남았어.\n당신 포옹으로만 충전된대!",
    prompt: "두 팔을 벌리고 충전 대기음을 내보세요.",
    gradient: "from-[#FFE0E5] to-[#FFB7C3]",
  },
  {
    id: "lover-02",
    targetIds: ["lover"],
    category: "농담",
    emoji: "🧭",
    eyebrow: "길을 잃은 마음",
    message: "혹시 지도 있어?\n당신 눈 보다가 또 길을 잃었거든.",
    prompt: "말한 뒤 스스로 오글거려 웃으면 성공이에요.",
    gradient: "from-[#FFE4D9] to-[#FFC0AF]",
  },
  {
    id: "lover-03",
    targetIds: ["lover"],
    category: "칭찬",
    emoji: "🎬",
    eyebrow: "내 하루의 베스트 장면",
    message: "오늘 있었던 일 중 제일 좋은 건\n지금 당신을 보는 일이야.",
    prompt: "영화 예고편 주인공을 소개하듯 말해주세요.",
    gradient: "from-[#F0E2FF] to-[#D7B9F5]",
  },
  {
    id: "lover-04",
    targetIds: ["lover"],
    category: "미션",
    emoji: "💓",
    eyebrow: "심쿵 눈맞춤 미션",
    message: "말없이 5초간 눈을 바라보다가\n동시에 가장 예쁜 표정 짓기!",
    prompt: "먼저 웃어버리는 사람이 사랑에 더 빠진 거래요.",
    gradient: "from-[#FFE0ED] to-[#F8B5D0]",
  },
  {
    id: "lover-05",
    targetIds: ["lover"],
    category: "유머",
    emoji: "🧾",
    eyebrow: "연애 영수증 발급",
    message: "오늘 당신 귀여움이 과다 결제됐습니다.\n환불은 뽀뽀로만 가능해요.",
    prompt: "손바닥을 영수증처럼 길게 펼쳐 보여주세요.",
    gradient: "from-[#FFF0C9] to-[#FFD28C]",
  },
  {
    id: "lover-06",
    targetIds: ["lover"],
    category: "응원",
    emoji: "🌙",
    eyebrow: "사랑하는 사람의 편",
    message: "오늘 힘들었던 마음은 내 옆에 내려놔.\n내가 반씩 들어줄게.",
    prompt: "말보다 따뜻한 손을 먼저 내밀어보세요.",
    gradient: "from-[#E4E8FF] to-[#BCC7F4]",
  },

  // 직장동료 — 회사에서 안전하게 터지는 공감 웃음
  {
    id: "coworker-01",
    targetIds: ["coworker"],
    category: "유머",
    emoji: "📊",
    eyebrow: "오늘의 업무 보고",
    message: "금일 웃음 실적이 부족합니다.\n지금 한 번 웃고 목표 달성하시죠!",
    prompt: "진지한 보고 톤으로 전달하면 효과가 커요.",
    gradient: "from-[#DDEBFF] to-[#ACC9F5]",
  },
  {
    id: "coworker-02",
    targetIds: ["coworker"],
    category: "농담",
    emoji: "☕",
    eyebrow: "직장인 3대 영양소",
    message: "직장인은 뭘 먹고 사는지 아세요?\n월급, 커피, 그리고 칼퇴 희망!",
    prompt: "커피잔으로 조용히 건배해주세요.",
    gradient: "from-[#F2E7D8] to-[#D8BFA0]",
  },
  {
    id: "coworker-03",
    targetIds: ["coworker"],
    category: "칭찬",
    emoji: "🏅",
    eyebrow: "동료가 주는 비공식 표창",
    message: "오늘 이 일이 굴러가는 데에는\n당신 몫이 정말 컸어요.",
    prompt: "도움받은 구체적인 한 가지를 덧붙여주세요.",
    gradient: "from-[#FFF0C8] to-[#FFD278]",
  },
  {
    id: "coworker-04",
    targetIds: ["coworker"],
    category: "미션",
    emoji: "🎙️",
    eyebrow: "퇴근 예고편 미션",
    message: "‘잠시 후, 주인공은 칼퇴합니다’를\n영화 예고편처럼 말하기!",
    prompt: "낮고 웅장한 목소리일수록 좋아요.",
    gradient: "from-[#E7E3FF] to-[#C9C0F6]",
  },
  {
    id: "coworker-05",
    targetIds: ["coworker"],
    category: "유머",
    emoji: "📧",
    eyebrow: "메일에는 없는 진짜 인사",
    message: "‘확인 부탁드립니다’ 말고 오늘은\n‘웃음 부탁드립니다’ 어떠세요?",
    prompt: "입으로 알림음을 낸 뒤 말해주세요.",
    gradient: "from-[#DFF5F4] to-[#AFE1DE]",
  },
  {
    id: "coworker-06",
    targetIds: ["coworker"],
    category: "응원",
    emoji: "🤝",
    eyebrow: "오늘도 같은 배를 탄 우리",
    message: "혼자 다 해내지 않아도 괜찮아요.\n우리 팀이잖아요.",
    prompt: "도울 일 하나를 먼저 물어봐 주세요.",
    gradient: "from-[#E1F5E7] to-[#B4E1C0]",
  },

  // 모르는 사람 — 부담 없이 건넬 수 있는 작은 친절
  {
    id: "stranger-01",
    targetIds: ["stranger"],
    category: "칭찬",
    emoji: "🌤️",
    eyebrow: "지나가다 발견한 좋은 기운",
    message: "오늘 분위기가 참 좋으시네요.\n덕분에 저도 기분이 좋아졌어요.",
    prompt: "짧고 밝게 말한 뒤 편안한 거리를 지켜주세요.",
    gradient: "from-[#E4F6EA] to-[#B9E5C5]",
  },
  {
    id: "stranger-02",
    targetIds: ["stranger"],
    category: "미션",
    emoji: "🚪",
    eyebrow: "3초 친절 미션",
    message: "뒤에 오는 사람을 위해\n문을 3초만 잡아주기!",
    prompt: "눈이 마주치면 가볍게 미소도 건네보세요.",
    gradient: "from-[#DFF2FF] to-[#AEDAF4]",
  },
  {
    id: "stranger-03",
    targetIds: ["stranger"],
    category: "유머",
    emoji: "🛗",
    eyebrow: "엘리베이터의 작은 마법",
    message: "닫힘 버튼보다 열림 버튼을 누르면\n오늘의 히어로가 될 수 있대요.",
    prompt: "상대가 타면 고개를 살짝 숙여 인사해주세요.",
    gradient: "from-[#FFF1C8] to-[#FFD47F]",
  },
  {
    id: "stranger-04",
    targetIds: ["stranger"],
    category: "응원",
    emoji: "📣",
    eyebrow: "짧아서 더 힘이 되는 말",
    message: "오늘도 좋은 하루 보내세요!\n분명 잘 풀릴 거예요.",
    prompt: "배달원이나 직원에게 감사와 함께 건네보세요.",
    gradient: "from-[#E8E3FF] to-[#CBC0F7]",
  },
  {
    id: "stranger-05",
    targetIds: ["stranger"],
    category: "칭찬",
    emoji: "🎨",
    eyebrow: "센스 포착 완료",
    message: "그 색 정말 잘 어울리세요.\n오늘 좋은 선택 하셨네요!",
    prompt: "외모보다 옷·소품·선택을 칭찬하면 더 편안해요.",
    gradient: "from-[#FFE2E0] to-[#FFBBB6]",
  },
  {
    id: "stranger-06",
    targetIds: ["stranger"],
    category: "미션",
    emoji: "💬",
    eyebrow: "감사 한 스푼 더하기",
    message: "평범한 ‘감사합니다’ 뒤에\n‘덕분에요’를 붙여보기!",
    prompt: "작은 진심이 상대의 표정을 바꿀 수 있어요.",
    gradient: "from-[#FFF0D5] to-[#FFD2A4]",
  },

  // 랜덤 — 누구에게나 건넬 수 있는 엉뚱한 웃음
  {
    id: "random-01",
    targetIds: ["random"],
    category: "유머",
    emoji: "🚨",
    eyebrow: "웃음 단속반 출동",
    message:
      "잠시 검문 있겠습니다.\n오늘 웃은 적 있으세요? 없으면 지금 웃으세요!",
    prompt: "손을 무전기처럼 들고 말해주세요.",
    gradient: "from-[#FFF0A8] to-[#FFD54F]",
  },
  {
    id: "random-02",
    targetIds: ["random"],
    category: "미션",
    emoji: "🤖",
    eyebrow: "인간 인증 미션",
    message: "로봇 목소리로 말하기:\n‘귀하의 미소가 감지되었습니다.’",
    prompt: "마지막에 기계처럼 엄지를 올려주세요.",
    gradient: "from-[#DDEBFF] to-[#AEC9F5]",
  },
  {
    id: "random-03",
    targetIds: ["random"],
    category: "농담",
    emoji: "🐟",
    eyebrow: "바다에서 건진 말장난",
    message: "물고기의 반대말은 뭘까요?\n불고기!",
    prompt: "정답 전에 3초간 심각하게 뜸을 들이세요.",
    gradient: "from-[#DDF4FA] to-[#A9DCE8]",
  },
  {
    id: "random-04",
    targetIds: ["random"],
    category: "미션",
    emoji: "🕺",
    eyebrow: "10초 웃음 처방전",
    message: "아무 음악이나 상상하며\n10초 동안 어깨춤 추기!",
    prompt: "먼저 시작하는 사람이 오늘의 분위기 메이커예요.",
    gradient: "from-[#E8E3FF] to-[#CFC4FF]",
  },
  {
    id: "random-05",
    targetIds: ["random"],
    category: "칭찬",
    emoji: "✨",
    eyebrow: "오늘 발견한 반짝임",
    message: "당신이 있어서\n지금 분위기가 한결 좋아졌어요.",
    prompt: "눈을 보고 천천히 진심을 전해보세요.",
    gradient: "from-[#FFE4DB] to-[#FFC9B8]",
  },
  {
    id: "random-06",
    targetIds: ["random"],
    category: "응원",
    emoji: "🚀",
    eyebrow: "다음 한 걸음을 위한 말",
    message: "완벽하지 않아도 출발은 출발!\n당신의 오늘을 응원해요.",
    prompt: "작은 박수 세 번과 함께 보내주세요.",
    gradient: "from-[#DFF6E5] to-[#ACE2B9]",
  },
] as const;
